### ISSUE TITLE
Memory leak in vMBMasterPortEventClose (IDFGH-11055)

### ISSUE THREAD

**Issue by dnebrich** [espressif/esp-modbus#36]
Hi,

Appears to be a copy/paste error causing a memory leak on mbc_master_destroy.  xQueueMasterHdl is used in the first if block instead of xEventGroupMasterHdl and then is set to NULL.

https://github.com/espressif/esp-modbus/blob/d311198e269feac3e65d04193b6baa29101b4cbf/freemodbus/port/portevent_m.c#L295-L313

Thanks.

**Comment by alisitsyn** [comment]
Hi @dnebrich,

Thank you for the issue. Don't know how it was happened. the issue confirmed and will be fixed in next release.

**Comment by alisitsyn** [comment]
Merged in v1.0.12 with commit 38f64e52997842850a8c182aec41f4994dd180f5
