### ISSUE TITLE
mbc_master_send_request - Exception Codes (IDFGH-12757)

### ISSUE THREAD

**Issue by dmglogowskiOS** [espressif/esp-modbus#60]
When `mbc_master_send_request` returns an `ESP_FAIL` to the caller, the documentation states that an exception or other failure occurred. However, it is unclear how to determine what might be the case, since:
1. ESP_FAIL indicates that either an exception occurred OR that there was another failure
2.  It is not clear if the modbus exception codes are accessible, when an exception occurred. 

Clarifying information, and adding to the documentation, about this would be helpful, since the documentation is currently quite ambiguous in this regard.

**Comment by alisitsyn** [comment]
@dmglogowskiOS,

Thank you for this issue. It is a very good question. Unfortunately, the current API do propagate the error code to indicate an exception but do not provide the way to determine the exact code of exception and the way of handling for this. I don't have nice solution for this but can provide the simple workarounds for this issue. One solution will not involve the changes in the library code.
I will provide update ASAP.

**Comment by alisitsyn** [comment]
@dmglogowskiOS,

I propose the workaround to add [the user error handler function](https://github.com/espressif/esp-modbus/pull/62/commits/17de1dd9dd265313a604ae765ff431198f813a8d#diff-dd92830e4ffcf57adb5d49bd716a026fea482b21638a01919a9be86cb9b472dbR494) to catch the exception code. It also allows to check the data buffers on user side this can be useful for some gateways.

Please take a look and let me know if this would work for you.

**Comment by dmglogowskiOS** [comment]
This may work quite well for most users imo, but I am unsure if it would be the best solution for my use case since I am working on a more object oriented (and C++ based) library based on esp-modbus and I am unsure how to implement this error handler in a manner that is compatible with my approach, although I do believe it should be possible.

**Comment by alisitsyn** [comment]
> I am unsure if it would be the best solution for my use case since I am working on a more object oriented (and C++ based) library based on esp-modbus and I am unsure how to implement this error handler in a manner that is compatible with my approach, although I do believe it should be possible.

I understand your requirement. It is still possible to implement this with the callback but can agree this is like workaround but not the nice approach to do. The best approach would be to propagate the possible exception codes to the subset error codes returned from  `mbc_serial_master_send_request()` but the original idea was to hide Modbus specifics (mb exceptions are) from higher layer and I would not want to change it now. Other way could be to implement some additional API to get the exception code related to latest completed Modbus IO request. This would change the API interface but in compatible way. Also, the approach selected for this needs to be implemented the same way in v2.0 stack. I am still thinking about better way for this. You can also propose your view to this.

**Comment by dmglogowskiOS** [comment]
I believe a possible way to handle this might be by adding either a function `mbc_serial_master_last_return()` which should return the last state (Either 0 or the exception code of the last exception) or adding an overload to `mbc_serial_master_send_request()`, either by making it an option configurable in the menuconfig or by adding a separate function (`mbc_serial_master_send_request_ret()` maybe?) where in addition to the request and the data, you also pass it a pointer to a return/metadata buffer. 

What could also work is by maybe refactoring the function to return this struct:

```c
typedef struct {
    const esp_err_t err;
    const uint8_t function_code;
    const uint8_t exception_code;
} slave_return_t
```

The caller can then read the error code from that structure and handle any exception accordingly, if the error code signifies an exception occured.

What may definitively be needed is an error code excplicitly alerting the program that an exception has occured, rather than `ESP_FAIL`...

**Comment by alisitsyn** [comment]
> Obviously this second approach would definitely break the current API.

This way will not be implemented.

> I believe a possible way to handle this might be by adding either a function

Your approach is a bit different with what I mentioned [the function mbc_master_get_transaction_info](https://github.com/espressif/esp-modbus/pull/62/files#diff-dd92830e4ffcf57adb5d49bd716a026fea482b21638a01919a9be86cb9b472dbR395)

**Comment by dmglogowskiOS** [comment]
That function would be almost *exactly* what I need and I could easily integrate this into my library

**Comment by alisitsyn** [comment]
Ok, good. This will be updated accordingly and let it keep as basic approach. I would keep the callback approach as well, because it can be useful in some other user use cases.

**Comment by alisitsyn** [comment]
This [old CPP wrapper](https://github.com/alisitsyn/modbus_support/blob/mb_support/modbus_add_cpp_wrapper) will probably help you.

**Comment by dmglogowskiOS** [comment]
Thanks but see my answer in the associated Repo.

**Comment by alisitsyn** [comment]
The issue has been fixed with commit 1eafc29df3d14ec379ea76f07337ae9816443e75

**Comment by alisitsyn** [comment]
The component release is a bit postponed for now.

**Comment by SputnikTheMighty** [comment]
Hey, is there an easy way to expose the exception codes with v2.x?

**Comment by alisitsyn** [comment]
Hey,

The v2 exposes more headers (as was requested by users) already in its [cmake](https://github.com/espressif/esp-modbus/blob/main/CMakeLists.txt#L48).
The [exception codes](https://github.com/espressif/esp-modbus/blob/main/modbus/mb_objects/common/mb_types.h#L92) are already exposed and the header can be included. If you need more internals to expose for your project you can do it through your project CMakeLists.txt.

Let me know if you need more information of examples.

**Comment by SputnikTheMighty** [comment]
How can I retrieve the exception code after a failed read? Do you have an example?

**Comment by alisitsyn** [comment]
example: 

1. Please read the [custom function handler section](https://docs.espressif.com/projects/esp-modbus/en/main/esp32/master_api_overview.html#modbus-api-master-handler-customization).

What you need: 
2. redefine your custom handler for all supported commands and keep its existing handler to be used later.
3. Call default handler from there (saved in structure as needed) in custom handler function call the existing handler for the function (saved). It returns an exception processed. Use this exception code as needed in your custom handler. You can get access to the original frame there through the frame PDU pointer.
4. Setup and start modbus master. It will execute the default handler for each command. Do whatever handling you need with exception code.
5. Destroy the master and repair saved default handlers back if needed.

The code below can be useful: 
```c
typedef struct mb_command_entry_s {
    uint8_t func_code;
    mb_fn_handler_fp real_func_handler;
} mb_command_entry_t;

static mb_command_entry_t custom_handlers[] = {
    { .func_code = MB_FUNC_READ_COILS },
    { .func_code = MB_FUNC_READ_DISCRETE_INPUTS },
    { .func_code = MB_FUNC_READ_HOLDING_REGISTER },
    { .func_code = MB_FUNC_READ_INPUT_REGISTER },
    { .func_code = MB_FUNC_WRITE_SINGLE_COIL },
    { .func_code = MB_FUNC_WRITE_REGISTER },
    { .func_code = MB_FUNC_WRITE_MULTIPLE_COILS },
    { .func_code = MB_FUNC_WRITE_MULTIPLE_REGISTERS },
    { .func_code = MB_FUNC_READWRITE_MULTIPLE_REGISTERS },
};

static mb_exception_t custom_handler(void *inst, uint8_t *frame_ptr, uint16_t *len)  {
      // raw example code to explain:
      uint8_t func_code = frame_ptr[0]; // the function code
      mb_fn_handler_fp real_handler = custom_handlers[func_code].real_func_handler;
      mb_exception_t exception = real_handler(void *inst, uint8_t *frame_ptr, uint16_t *len);
      // Other user code as needed.
      return exception;
}

static esp_err_t register_custom_handler(mb_command_entry_t *entry, mb_fn_handler_fp handler)
{
    if (!entry || !entry->func_code || entry->func_code >= MB_FUNC_ERROR) {
        ESP_LOGE(TAG, "Incorrect function entry pointer.");
        return ESP_ERR_INVALID_ARG;
    }
    mb_fn_handler_fp new_handler = handler ? handler : entry->real_func_handler ? entry->real_func_handler : NULL;

    // Override the standard function handlers to map frames to external node
    esp_err_t err = mbc_get_handler(tcp_slave_handle, entry->func_code, &entry->real_func_handler);
    ESP_RETURN_ON_ERROR(err, TAG, "Cannot get original function handler (%u).", entry->func_code);
    ESP_LOGD(TAG, "Override the standard function (%u) handler to %p",
             entry->func_code, new_handler);
    err = mbc_delete_handler(tcp_slave_handle, entry->func_code);
    if (err != ESP_OK && err != ESP_ERR_INVALID_STATE) {
        ESP_LOGE(TAG, "Cannot delete standard function (%u) handler %p", entry->func_code, entry->real_func_handler);
        return err;
    }
    return mbc_set_handler(tcp_slave_handle, entry->func_code, new_handler);
}    

// In master init function:
     for (size_t i = 0; i < sizeof(custom_handlers) / sizeof(custom_handlers[0]); ++i) {
        ESP_RETURN_ON_ERROR(register_custom_handler(&custom_handlers[i], custom_handler),
                            TAG, "Register custom handler %u, failed.", custom_handlers[i].func_code);
    }


```
