### ISSUE TITLE
Has "mbfuncinput.c" file a bug? (IDFGH-13284)

### ISSUE THREAD

**Issue by NOM-99** [espressif/esp-modbus#66]
Tools Used:
 - IDE       -> VS-2019 16.11.33 / VisualGDB-5.6R9-4777 over Windows 11.
- Toolchain -> 8.4.0/8.1.0/r9
 - Framework -> ESP-IDF v4.4.3

Good afternoon,

Right now, I am using the "esp-modbus" component to work as a slave with a Modbus-RTU communication, 9600 baud rate, without parity and with two stop bits. I am triying to read 125 Holding registers and 125 Input registers.

When the Holding registers are read the communication is correct between the master and the slave; however, when the Input registers are read the communication returns "Modbus illegal data value" messages. Therefore, investigating the files that manage these communication functions I have found that in the Holding registers reading function the maximum number of registers that can be read are 125 and in the Input registers reading function the maximum number of registers that can be read are 124. 

Screenshots of "**mbfuncholding.c**" file of the "**eMBFuncReadHoldingRegister()**" function:

![Captura de pantalla 2024-07-18 141821](https://github.com/user-attachments/assets/2cf61c92-42f3-48e1-982c-1500d4ad0f5a)
![image](https://github.com/user-attachments/assets/460b23e9-12db-4f9c-9c8b-5e7b7d4fe1f0)

Screenshots of "**mbfuncinput.c**" file of the "**eMBFuncReadInputRegister()**" function:

![image](https://github.com/user-attachments/assets/fb771a33-5182-4bf9-a1e3-d59ec2d50533)
![image](https://github.com/user-attachments/assets/837ee9ea-5c69-4b7d-b176-165e1a7456bd)

I have read the documentation "Modbus application protocol specification" and the reading limit of the Holding and Input registers should be the same, 125.

![image](https://github.com/user-attachments/assets/a10e7292-b4b9-4f75-97d4-edf4ca77a5aa)
![image](https://github.com/user-attachments/assets/e10f2dd9-88c0-4d1c-897f-48e7303c27ab)

I would like to know if this is really a bug of the file "mbfuncinput.c" or if this limit has become different for some particular reason.

Thank you very much.

**Comment by NOM-99** [comment]
Thank you very much.

**Comment by alisitsyn** [comment]
@NOM-99 ,

Thank you for your attention to this.
