### ISSUE TITLE
Add core affinity setting for tcp_slave (IDFGH-7653)

### ISSUE THREAD

**Issue by allard-potma** [espressif/esp-modbus#7]
Earlier I requested core affinity to be put in this component: [https://github.com/espressif/esp-idf/issues/6700](ESP-IDF #6700). I seems that the task "tcp_server_task" in port_tcp_slave.c is missed, it still uses xTaskCreate instead of xTaskCreatePinnedToCore.

**Comment by alisitsyn** [comment]
@allard-potma , 

Thank you for this finding. At some stage the change you described disappeared. It will be fixed soon.

**Comment by alisitsyn** [comment]
Fixed with the commit: 28ebfb1712a5b35cff80545009b1abab925a670d
