### ISSUE TITLE
run both tcp and rtu slave at same time  (IDFGH-7663)

### ISSUE THREAD

**Issue by ahosny333** [espressif/esp-modbus#8]
hi,
is there any suggestion to run both RTU and TCP slave modbus at same time at same board ?

**Comment by alisitsyn** [comment]
Hi @ahosny333,

Unfortunately, it is not possible to use RTU slave  + TCP slave on the same board for now. It is possible to use one instance of a master and one instance of a slave at the same time.

**Comment by jmichelx2** [comment]
Hi,

Is is possible to run RTU master on UART1 and a RTU slave on UART2 in the same application?

Is there any future possibility to run two RTU masters on two UARTS in the same application?

**Comment by alisitsyn** [comment]
This issue is related to https://github.com/espressif/esp-modbus/issues/9.
This feature request is in progress and will be implemented in modbus stack v2.0.0_beta1.

**Comment by alisitsyn** [comment]
Closed as duplicate.
