### ISSUE TITLE
Change the modbusTCP slave port number (IDFGH-13995)

### ISSUE THREAD

**Issue by iamugly** [espressif/esp-modbus#81]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

I would like to provide a way to modify the modbusTCP port number

### Use cases

Some scenarios may need to be modified

**Comment by alisitsyn** [comment]
@iamugly,

The slave Modbus port is configurable through the [kconfig value](https://github.com/espressif/esp-modbus/blob/master/Kconfig#L9) in stack version v1.0.x. For the stack v2.0.0-beta, the TCP port is configurable independently in [the slave configuration structure](https://github.com/espressif/esp-modbus/blob/release/v2.0/examples/tcp/mb_tcp_slave/main/tcp_slave.c#L396) for each instance of master and slave.

**Comment by alisitsyn** [comment]
@iamugly,

Does this solve the issue you described? Could you provide some feedback?

**Comment by alisitsyn** [comment]
The issue is closed due to lack of feedback.
